* [32mmain[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/add-contrib[m
  [31mremotes/origin/add-docs-site-previews[m
  [31mremotes/origin/add-example-readmes[m
  [31mremotes/origin/add-httprr-and-test-utilities[m
  [31mremotes/origin/add-linting[m
  [31mremotes/origin/add-watsonx[m
  [31mremotes/origin/agents-package-api-improvements[m
  [31mremotes/origin/analysis/value-vs-pointer-receivers[m
  [31mremotes/origin/anthropic-improvements[m
  [31mremotes/origin/anthropic-improvements.1[m
  [31mremotes/origin/anthropic-thinking-demo-standalone[m
  [31mremotes/origin/dependabot/go_modules/examples/llmsummarization-chain-example/golang.org/x/net-0.33.0[m
  [31mremotes/origin/dependabot/go_modules/examples/mistral-embedding-example/golang.org/x/crypto-0.31.0[m
  [31mremotes/origin/dependabot/go_modules/github.com/containerd/containerd-1.7.27[m
  [31mremotes/origin/dependabot/go_modules/golang.org/x/crypto-0.35.0[m
  [31mremotes/origin/dependabot/go_modules/golang.org/x/net-0.38.0[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/babel/helpers-7.27.0[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/babel/runtime-7.27.0[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/babel/runtime-corejs3-7.27.0[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/estree-util-value-to-estree-3.3.3[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/http-proxy-middleware-2.0.9[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/image-size-1.2.1[m
  [31mremotes/origin/dependabot/npm_and_yarn/docs/prismjs-1.30.0[m
  [31mremotes/origin/devin/1734592248-add-stop-sequence-support[m
  [31mremotes/origin/docs-fix-api-references[m
  [31mremotes/origin/docs_site_preview_in_ci[m
  [31mremotes/origin/feat/add-nova-aws-bedrock-models[m
  [31mremotes/origin/feat/ollama-context-option[m
  [31mremotes/origin/feature/anthropic-generic-prompt-caching[m
  [31mremotes/origin/feature/deepseek-integration-improvements[m
  [31mremotes/origin/feature/token-based-memory-flushing[m
  [31mremotes/origin/fix-636[m
  [31mremotes/origin/fix-groq-max-tokens[m
  [31mremotes/origin/fix-linting-examples-and-testcontainers[m
  [31mremotes/origin/fix-remaining-test-failures[m
  [31mremotes/origin/fixup-github-lint[m
  [31mremotes/origin/gh-pages[m
  [31mremotes/origin/googleai-shared-tests[m
  [31mremotes/origin/gpt4-turbo-example[m
  [31mremotes/origin/gpt4-vision-support[m
  [31mremotes/origin/image-det[m
  [31mremotes/origin/improve-mrkl-example[m
  [31mremotes/origin/investigate-issue-1391[m
  [31mremotes/origin/main[m
  [31mremotes/origin/oldmain[m
  [31mremotes/origin/ollama[m
  [31mremotes/origin/openai-compat-max-tokens[m
  [31mremotes/origin/pr-1083[m
  [31mremotes/origin/pr-1415[m
  [31mremotes/origin/pr-448[m
  [31mremotes/origin/pre-v0.1.2[m
  [31mremotes/origin/prompt-caching-support[m
  [31mremotes/origin/proposal/typed-chain-interface[m
  [31mremotes/origin/qdrant-backend[m
  [31mremotes/origin/revert-1125-openai-resoning[m
  [31mremotes/origin/streaming-iter-seq2[m
  [31mremotes/origin/test-fixes-clean[m
  [31mremotes/origin/thinking-tokens-core[m
  [31mremotes/origin/thinking-tokens-demo[m
  [31mremotes/origin/tmc-mongovector-improvements[m
  [31mremotes/origin/update-example[m
  [31mremotes/origin/update-examples-latest-tag[m
  [31mremotes/origin/update-golangci-lint[m
  [31mremotes/origin/various-provider-fixes[m
  [31mremotes/origin/vertex-gemini-embeddings[m
  [31mremotes/origin/xiazemin/main[m
